carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
    path('api/get-occupied-times/', views.get_occupied_times, name='get_occupied_times'),
]

repair_service/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from repair_service import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('repair_app.urls', namespace='repair_app')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),
]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from goods.models import Service
from users.models import User


# Create your models here.

class CartQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(to=Service, on_delete=models.CASCADE, verbose_name='Услуга')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'cart'
        verbose_name = "Корзина"
        verbose_name_plural = "Корзина"
        ordering = ("product",)

    objects = CartQueryset().as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        if self.user:
            return f'Корзина {self.user.username} | Товар {self.product.service_name} | Количество {self.quantity}'

        return f'Анонимная корзина | Товар {self.product.service_name} | Количество {self.quantity}'

carts/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from carts.utils import get_user_carts
from goods.models import Service
from carts.models import Cart


# Create your views here.

# Представление для добавления услуги в корзину.
# Получает ID услуги из POST-запроса и либо увеличивает количество,
# либо создаёт новую запись в корзине (в зависимости от авторизации пользователя).
def cart_add(request):
    product_id = request.POST.get("product_id")
    product = Service.objects.get(id=product_id)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)
        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)

    else:
        carts = Cart.objects.filter(
            session_key=request.session.session_key, product=product)
        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(
                session_key=request.session.session_key, product=product, quantity=1)

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request)
    response_data = {
        "message": "Товар добавлен в корзину",
        "cart_items_html": cart_items_html,
    }
    return JsonResponse(response_data)

# Представление для изменения количества услуги в корзине.
# Получает ID позиции и новое количество из POST-запроса, обновляет значение
# и возвращает обновлённую HTML-разметку корзины.
def cart_change(request):
    cart_id = request.POST.get("cart_id")
    quantity = request.POST.get("quantity")

    cart = Cart.objects.get(id=cart_id)

    cart.quantity = quantity
    cart.save()
    updated_quantity = cart.quantity

    cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": cart}, request=request)

    response_data = {
        "message": "Количество изменено",
        "cart_items_html": cart_items_html,
        "quantity": updated_quantity,
    }

    return JsonResponse(response_data)

# Представление для удаления услуги из корзины.
# Получает ID позиции из POST-запроса, удаляет её из корзины
# и возвращает HTML корзины без удалённого элемента.
def cart_remove(request):
    cart_id = request.POST.get("cart_id")

    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request)

    response_data = {
        "message": "Товар удален",
        "cart_items_html": cart_items_html,
        "quantity_deleted": quantity,
    }

    return JsonResponse(response_data)

carts/templates/carts/includes/included_cart.html
{% load static %}

<div class="card mb-3 text-bg-light ">
    {% for cart in carts %}
        <div class="card-header">
            <h5 class="card-title">Услуга: {{ cart.product.service_name }} | Категория: {{ cart.product.category }}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row text-center">
                    <div class="col p-0">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm decrement"
                                    data-cart-id="{{ cart.id }}"
                                    data-cart-change-url="{% url "cart:cart_change" %}">
                                    {% csrf_token %}
                                    -</button>
                            </span>
                            <input type="text" class="form-control number" value="{{ cart.quantity }}"
                                readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm increment"
                                    data-cart-id="{{ cart.id }}"
                                    data-cart-change-url="{% url "cart:cart_change" %}">
                                    {% csrf_token %}
                                    +</button>
                            </span>
                        </div>
                    </div>
                    <div class="col p-0">
                        <p>x {{ cart.product.sell_price }} = </p>
                    </div>
                    <div class="col p-0"><strong> {{cart.products_price}} руб.</strong></div>
                    <div class="col p-0">
                        <a href="{% url "cart:cart_remove" %}" class="remove-from-cart"
                        data-cart-id="{{ cart.id }}">
                            {% csrf_token %}
                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                alt="Catalog Icon" width="16" height="16">
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
</div>
<div class="card mb-3 ">
    <div class="card-footer">
        <p class="float-left">Итого <strong>{{ carts.total_quantity }}</strong> услуг(а) на сумму</p>
        <h4 class="float-left"><strong>{{ carts.total_price }} рублей</strong></h4>
    </div>
</div>
{% if carts and not order %}
<a class="btn btn-dark" href="{% url 'orders:create_order' %}">
Оформить заказ
</a>
{% endif %}