carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

repair_service/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from repair_service import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('repair_app.urls', namespace='repair_app')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),
]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
    path('admin/orders/', views.admin_orders, name='admin_orders'),
    path('staff/orders/', views.staff_orders, name='staff_orders'),
    path('orders/item/<int:item_id>/toggle_picked/', views.toggle_picked_status, name='toggle_picked_status'),
    path('toggle_all_tasks_status/<int:order_id>/', views.toggle_all_tasks_status, name='toggle_all_tasks_status'),
    path("admin/reports/", views.create_report, name="admin_reports"),
    path('profile/cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
]

orders/models.py
from django.db import models
from users.models import User
from users.models import Employee
from goods.models import Service


class OrderitemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Status(models.Model):
    status_name = models.CharField(max_length=150, verbose_name="Название статуса")
    status_category = models.CharField(max_length=150, null=True, verbose_name="Категория статуса (Заказ/Услуга)")
    status_description = models.CharField(max_length=150, verbose_name="Описание статуса")

    class Meta:
        db_table = "status"
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"

    def __str__(self):
        return f"Статус : {self.status_name}"


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь",
                             default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name="Требуется забрать на ремонт с адреса")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес для забирания на ремонт")
    delivery_date = models.DateField(null=True, verbose_name='Дата доставки/получения на ремонт')
    delivery_time = models.TimeField(null=True, verbose_name='Время доставки/получения на ремонт')
    order_finished_datetime = models.DateTimeField(default=None, blank=True, null=True,
                                                   verbose_name='Дата завершения заказа')
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при получении")
    comment = models.TextField(null=True, blank=True, verbose_name="Комментарий клиента")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.ForeignKey(to=Status, on_delete=models.SET_DEFAULT, blank=True, null=True, default=1,
                               limit_choices_to={'status_category': 'Заказ'}, verbose_name="Статус заказа")

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Service, on_delete=models.SET_DEFAULT, null=True, verbose_name="Услуга",
                                default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")
    status = models.ForeignKey(to=Status, on_delete=models.SET_DEFAULT, default=6,
                               limit_choices_to={'status_category': 'Услуга'}, verbose_name="Статус услуги")

    employee = models.ForeignKey(to=Employee, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None,
                                 verbose_name="Назначен сотруднику")

    work_ended_datetime = models.DateTimeField(default=None, blank=True, null=True,
                                               verbose_name='Дата и время выполнения')

    class Meta:
        db_table = "order_item"
        verbose_name = "Заказанная услуга"
        verbose_name_plural = "Заказанные услуги"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.price() * self.quantity, 2)

    def __str__(self):
        return f"Услуга {self.name} | Заказ № {self.order.pk}"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from goods.models import Category


# Create your models here.
class User(AbstractUser):
    class Meta:
        db_table = 'users'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    image = models.ImageField(upload_to='users_image', blank=True, null=True, verbose_name='Аватар')


# Модель Employee
class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'employee'
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        ordering = ("id",)

    def __str__(self):
        return f"{self.user.username} - {self.category.category_name}"

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username',
                  'password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name',
                  'last_name',
                  'username',
                  'email',
                  'password1',
                  'password2',
                  )


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('image',
                  'first_name',
                  'last_name',
                  'username',
                  'email',
                  )

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock %}

{% block content %}
 <div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded ">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form action="{% url "user:login" %}" method="post">
                {% csrf_token %}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}

                <div class="mb-3">
                <label for="username" class="form-label">Имя пользователя</label>
                <input type="text" class="form-control"
                       value="{% if form.username.value %}{{ form.username.value}}{% endif %}"
                       name="username" id="id_username"
                       placeholder="Введите ваше имя пользователя" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Пароль</label>
                    <input type="password" class="form-control"
                           name="password" id="id_password"
                           placeholder="Введите ваш пароль" required>
                </div>

                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form>
                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url "users:registration" %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/google.svg"%}" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/facebook.svg"%}" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/github.svg"%}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}
{% load multiply %}

{% block content %}
<div class="container-fluid">
    <div class="row mt-1">
        <div class="col-lg-12">
            <div class="bg-white p-4 mb-4 rounded">
                <h3 class="text-center mb-6">Профиль пользователя</h3>
                <form action="{% url 'user:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4 mb-3 text-center">
                            {% if user.image %}
                                <img src="{{ user.image.url }}"
                                     alt="Аватар пользователя" class="img-fluid rounded-circle"
                                     style="max-width: 155px;">
                            {% else %}
                                <img src="{% static 'deps/images/baseavatar.jpg' %}"
                                     alt="Аватар пользователя" class="img-fluid rounded-circle"
                                     style="max-width: 155px;">
                            {% endif %}
                            <input type="file" class="form-control mt-3" id="id_image" name="image" accept="image/*">
                            {% if form.image.errors %}
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    {{ form.image.errors }}
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-3 mb-2">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name" name="first_name"
                                   placeholder="Введите ваше имя" value="{{ form.first_name.value }}" required>

                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name" name="last_name"
                                   placeholder="Введите вашу фамилию" value="{{ form.last_name.value }}" required>
                        </div>

                        <div class="col-md-3 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username" name="username"
                                   placeholder="Введите ваше имя пользователя" value="{{ form.username.value }}" required>

                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email" name="email"
                                   placeholder="Введите ваш email" value="{{ form.email.value }}" required>
                        </div>

                        <div class="d-flex align-items-end justify-content-end col-md-3">
                            <button type="submit" onclick="return confirmProfileUpdate()" class="btn btn-dark w-100">Сохранить</button>
                            <script>
                            function confirmProfileUpdate() {
                                return confirm("Вы уверены, что хотите обновить данные профиля?");
                            }
                            </script>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!-- Блок поиска по заказам -->
        <div class="col-12">
            <div class="bg-white p-4 mb-4 rounded">
                <h3 class="text-center mb-4">Поиск по заказам</h3>
                <form method="get" action="{% url 'user:profile' %}">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="order_search" placeholder="Поиск по номеру заказа или статусу"
                               value="{{ request.GET.order_search }}">
                        <button class="btn btn-outline-secondary" type="submit">Искать</button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Блок профиля пользователя -->
        <div class="col-12">
            <div class="bg-white p-4 mb-4 rounded">
                <h3 class="text-center mb-4">Мои заказы</h3>
                <div class="container">
                    <div class="accordion" id="accordionExample">
                        {% for order in orders %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ order.id }}">
                                <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}"
                                        type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}"
                                        aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                    Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{ order.status.status_name }}</strong>
                                </button>
                            </h2>
                            <div id="collapse{{ order.id }}"
                                 class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}"
                                 aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p><strong>Информация о заказе №{{ order.id }}</strong> </p>
                                    <p><strong>Общая сумма: </strong>{{ order.total }} руб.</p>

                                    {% if order.requires_delivery %}
                                    <p><strong>Требуется выезд сотрудника:</strong> Да </p>
                                    {% else %}
                                    <p><strong>Требуется выезд: </strong>Нет </p>
                                    {% endif %}

                                    {% if order.delivery_address %}
                                    <p><strong>Адрес для выездного забора средства в сервис:</strong> {{ order.delivery_address }}</p>
                                    <p><strong>Дата и время выездного забора средства в сервис:</strong> {{ order.delivery_date }} в <strong>{{ order.delivery_time }} МСК</strong> </p>
                                    {% else %}
                                    <p><strong>Адрес для сдачи средства в сервис: </strong>г. Альметьевск, ул. Примерная 116</p>
                                    <p><strong>Дата и время для сдачи средства в сервис:</strong> {{ order.delivery_date }} в {{ order.delivery_time }} МСК </p>
                                    {% endif %}
                                    <p><strong>Комментарий: </strong>"{{ order.comment }}"</p>
                                    <p><strong>Состав заказа в таблице:</strong></p>
                                    <table class="table table-dark table-hover">
                                        <thead>
                                            <tr>
                                                <th>Услуга</th>
                                                <th>Количество</th>
                                                <th>Цена</th>
                                                <th>Общая стоимость</th>
                                                <th>Статус</th>
                                                <th>Дата и время выполнения</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in order.orderitem_set.all %}
                                            <tr>
                                                <td><a class="text-white" href="{% url 'goods:product' item.product.slug %}">{{ item.product.service_name }} | {{ item.product.category }}</a></td>
                                                <td>{{ item.quantity }}</td>
                                                <td>{{ item.price }}</td>
                                                <td>{{ item.quantity|multiply:item.price|floatformat:2 }} руб.</td>
                                                <td>{{ item.status.status_name }} </td>
                                                {% if item.work_ended_datetime %}
                                                <td>{{ item.work_ended_datetime }} </td>
                                                {% else %}
                                                <td> - </td>
                                                {% endif %}
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                     {% if order.status.id == 1 %}
                                     <form method="post" action="{% url 'users:cancel_order' order.id %}" onsubmit="return confirmCancelOrder();">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger ">Отменить заказ</button>
                                     </form>
                                     <script>
                                        function confirmCancelOrder() {
                                            return confirm("Вы уверены, что хотите отменить заказ?");
                                        }
                                     </script>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock %}


{% block content %}
   <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded ">
                    <h2 class="text-center mb-4">Регистрация</h2>
                    <form action="{% url "user:registration" %}" method="post" >
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                   value="{% if form.first_name.value %}{{ form.first_name.value}}{% endif %}"
                                    name="first_name"
                                    placeholder="Введите ваше имя" required>
                                    {% if form.first_name.errors %}
                                    <!-- Для non_field_erors  -->
                                        <div class="alert alert-danger alert-dismissible fade show " role="alert">
                                            {{form.first_name.errors}}
                                        </div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                       value="{% if form.last_name.value %}{{ form.last_name.value}}{% endif %}"
                                       name="last_name"
                                    placeholder="Введите вашу фамилию" required>
                                    {% if form.last_name.errors %}
                                    <!-- Для non_field_erors  -->
                                        <div class="alert alert-danger alert-dismissible fade show " role="alert">
                                            {{form.last_name.errors}}
                                        </div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                       value="{% if form.username.value %}{{ form.username.value}}{% endif %}"
                                       name="username"
                                    placeholder="Введите ваше имя пользователя" required>
                                    {% if form.username.errors %}
                                    <!-- Для non_field_erors  -->
                                        <div class="alert alert-danger alert-dismissible fade show " role="alert">
                                            {{form.username.errors}}
                                        </div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                       value="{% if form.email.value %}{{ form.email.value}}{% endif %}"
                                       name="email"
                                    placeholder="Введите ваш email" required>
                                    {% if form.email.errors %}
                                    <!-- Для non_field_erors  -->
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                            {{form.email.errors}}
                                        </div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Пароль*</label>
                                <input type="password" class="form-control" id="id_password1"
                                       value="{% if form.password1.value %}{{ form.password1.value}}{% endif %}"
                                       name="password1"
                                    placeholder="Введите пароль" required>
                                    {% if form.password1.errors %}
                                    <!-- Для non_field_erors  -->
                                        <div class="alert alert-danger alert-dismissible fade show " role="alert">
                                            {{form.password1.errors}}
                                        </div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                <input type="password" class="form-control" id="id_password2"
                                       value="{% if form.password2.value %}{{ form.password2.value}}{% endif %}"
                                       name="password2"
                                    placeholder="Подтвердите пароль" required>
                                    {% if form.password2.errors %}
                                    <!-- Для non_field_erors  -->
                                        <div class="alert alert-danger alert-dismissible fade show " role="alert">
                                            {{form.password2.errors}}
                                        </div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}


{% block content %}

{% user_carts request as carts %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded ">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "carts/includes/included_cart.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}